// DELETE THIS AFTER YOU CREATE THE FIRST FILE INSIDE THE STORE FOLDER

/*
    THIS FILE CONTAINS VARIABLES USED TO GET VALUES FROM THE REDUCER'S STATE
*/

export const selectMyData = (state) => state.sampleSlice.myData;
