// DELETE THIS AFTER YOU CREATE THE FIRST FILE INSIDE THIS FOLDER

/*
    THIS FOLDER WILL CONTAIN FILES THAT ARE USED TO HANDLE DIFFERENT FUNCTIONALITIES, CALCULATIONS &LOGICS.
    EX: Date conversions, Generate colors, etc.
*/
