// DELETE THIS AFTER YOU CREATE THE FIRST COMPONENT INSIDE THIS FOLDER

/*
    THIS FOLDER WILL CONTAIN COMPONENTS THAT ARE USED TO HANDLE SOME APP'S FUNCTIONALITIES.
    EX: LOADER, etc.
*/

const Layout = () => {
  return <div>Layout</div>;
};

export default Layout;
